default_linemode:
    enabled: true
fix_chars_width:
    enabled: false

# example to fix emoji chars width
# fix_chars_width:
#     enabled: true
#     force_right_align: false
#     for_term:
#         default:
#             - "ğŸï¸"
#             - "âœï¸"
#             - "âš™ï¸" 
#             - "ğŸ•³ï¸"
#             - "ğŸ—ƒï¸"
#             - "â¬‡ï¸"
#             - "ğŸ–¼ï¸"
#             - "ğŸï¸"
