default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/Vimjas/vint
    rev: v0.4a3
    hooks:
      - id: vint
        types: [file]
        files: (\.vim$|vimrc$)
        exclude: plug\.vim$

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]
        files: \.sh$

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        files: \.sh$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            feat,
            fix,
            build,
            ci,
            chore,
            docs,
            drop,
            edit,
            perf,
            polish,
            root,
            refactor,
            revert,
            style,
            temp,
            tests,
          ]
